/** Local rendered page exercising the production DOM boundary. No account IO. */
export const browserFixture = `<!doctype html><html><head><meta charset="utf-8"><title>Local browser boundary</title><style>
body{font-family:system-ui;margin:20px}.markdown,[data-user-message-bubble]{white-space:pre-wrap}[contenteditable]{white-space:pre-wrap;min-height:60px;border:1px solid;padding:10px}[hidden]{display:none!important}button{padding:5px;margin:3px}[role=slider]{height:20px;width:180px;background:#aaa}
</style></head><body><main id="history"></main><form data-chatgpt-composer>
<button id="effort" type="button" data-codex-intelligence-trigger="true" data-composer-navigation-target="reasoning" aria-haspopup="menu" aria-expanded="false">Medium</button>
<div id="menu" role="menu" hidden><div role="menuitem" tabindex="0"><div data-model-picker-power-slider><div role="slider" aria-valuemin="0" aria-valuemax="4" aria-valuenow="1"></div></div></div></div>
<div id="prompt-textarea" data-composer-markdown role="textbox" contenteditable="true"></div>
<div id="mentions" data-mention-list-scroll-area hidden><button type="button" data-list-navigation-item="true">Codex Native2</button></div>
<input type="file" multiple><button id="send" type="submit">Send</button><button id="stop" type="button" aria-label="Stop" hidden>Stop</button></form>
<script>
const $=id=>document.getElementById(id);const labels=['Instant','Medium','High','Extra High','Pro'];let level=1;let assistant;let counter=0;
window.fixture={sends:0,stops:0,auto:false,finish(text){if(!assistant)return;assistant.innerHTML='';const content=document.createElement('div');content.className='markdown';content.textContent=text;assistant.append(content);const controls=document.createElement('div');controls.className='turn-action-controls';const button=document.createElement('button');button.textContent='Copy';controls.append(button);assistant.append(controls);$('stop').hidden=true;}};
$('effort').onclick=()=>{const show=$('menu').hidden;$('menu').hidden=!show;$('effort').setAttribute('aria-expanded',String(show));};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('menu').hidden=true;$('effort').setAttribute('aria-expanded','false');$('effort').textContent=labels[level];}if(!$('menu').hidden&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){level=Math.max(0,Math.min(4,level+(e.key==='ArrowLeft'?-1:1)));document.querySelector('[role=slider]').setAttribute('aria-valuenow',String(level));e.preventDefault();}});
$('prompt-textarea').addEventListener('input',()=>{$('mentions').hidden=$('prompt-textarea').innerText.trim()!=='@codex';});
$('mentions').querySelector('button').onclick=()=>{$('prompt-textarea').innerHTML='<span app-mention-path="app://local" app-mention-display-name="Codex Native2" contenteditable="false">Codex Native2</span> ';$('mentions').hidden=true;$('prompt-textarea').focus();const range=document.createRange();range.selectNodeContents($('prompt-textarea'));range.collapse(false);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);};
document.querySelector('input[type=file]').onchange=e=>{for(const file of e.target.files){const receipt=document.createElement('span');receipt.textContent=file.name;document.querySelector('form').append(receipt);}};
document.querySelector('form').onsubmit=e=>{e.preventDefault();window.fixture.sends++;counter++;const user=document.createElement('section');user.setAttribute('data-turn-key','user:'+counter);const bubble=document.createElement('div');bubble.setAttribute('data-user-message-bubble','');bubble.textContent=$('prompt-textarea').innerText;user.append(bubble);$('history').append(user);$('prompt-textarea').innerHTML='';assistant=document.createElement('section');assistant.setAttribute('data-turn-key','assistant:'+counter);assistant.setAttribute('data-conversation-role','assistant');$('history').append(assistant);$('stop').hidden=false;if(window.fixture.auto)setTimeout(()=>window.fixture.finish('fixture completed'),50);};
$('stop').onclick=()=>{window.fixture.stops++;$('stop').hidden=true;const badge=document.createElement('span');badge.setAttribute('data-testid','stopped-thinking');assistant?.append(badge);};
</script></body></html>`;
